---
name: go-zetasqlfmt
description: run go-zetasqlfmt
inputs:
  working-directory:
    description: file paths
    required: false
    default: .
  path:
    description: file paths
    required: true
  nosemicolon:
    description: no semicolon option
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.path }}
    - ${{ inputs.nosemicolon }}
