---
name: go-zetasqlfmt
description: run go-zetasqlfmt
inputs:
  path:
    description: file paths
    required: true
  nosemicolon:
    description: no semicolon option
    required: false
runs:
  using: docker
  image: docker://nametake/go-zetasqlfmt-action:v1
  args:
  - ${{ inputs.path }}
